s/PERSON/person/g
s/OBSERVATION_PERIOD/observation_period/g
s/VISIT_OCCURRENCE/visit_occurrence/g
s/CONDITION_OCCURRENCE/condition_occurrence/g
s/DRUG_EXPOSURE/drug_exposure/g
s/PROCEDURE_OCCURRENCE/procedure_occurrence/g
s/MEASUREMENT/measurement/g
s/OBSERVATION/observation/g
s/LOCATION/location/g
s/CARE_SITE/care_site/g
s/PROVIDER/provider/g
s/DEATH/death/g
s/DRUG_ERA/drug_era/g
s/CONDITION_ERA/condition_era/g
s/OBSERVATION_PERIOD/observation_period/g
s/DRUG_ERA/drug_era/g
s/CONDITION_ERA/condition_era/g
s/N3C_PRE_COHORT/n3c_pre_cohort/g
s/N3C_CLINICAL_COHORT/n3c_clinical_cohort/g
